apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-static
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.6
    path: "/opt/nfs/storage-static"
