apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 2
  labels:
    run: hawkbit
  name: hawkbit
  namespace: titan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hawkbit
    spec:
      containers:
      - name: hawkbit
        image: milocasagrande/hawkbit-docker
        tty: true
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
