apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 2
  labels:
    run: redis
  name: redis
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
