apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 2
  labels:
    run: simple-storage
  name: simple-storage
  namespace: titan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: simple-storage
    spec:
      containers:
      - name: simple-storage
        image: milocasagrande/simple-storage
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: storage
          mountPath: "/mnt/artifacts"
        - name: storage-static
          mountPath: "/mnt/artifacts-static"
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      - name: storage-static
        persistentVolumeClaim:
          claimName: storage-static
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
