apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 2
  labels:
    run: lava-dev
  name: lava-dev
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lava
    spec:
      containers:
      - name: lava-dev
        image: forcedinductionz/lava-docker:testing
        ports:
        - containerPort: 80
        stdin: true
        tty: true
        securityContext:
          privileged: true
      volumes:
      - name: dev
        hostPath:
          path: /dev
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
