apiVersion: v1
kind: Pod
metadata:
  generateName: zephyr-ci-
  labels:
    app: zephyr-ci
  namespace: titan
spec:
  containers:
    - name: zephyr-builder
      image: forcedinductionz/ubuntu-zephyr:las16
      stdin: true
      tty: true
      ports:
        - containerPort: 8000
