apiVersion: v1
kind: Pod
metadata:
  generateName: zephyr-ci-
  labels:
    app: zephyr-ci
  namespace: titan
spec:
  containers:
    - name: zephyr-builder
      image: forcedinductionz/ubuntu-zephyr:las16
      imagePullPolicy: Always
      stdin: true
      tty: true
      volumeMounts:
      - name: storage
        mountPath: "/mnt/artifacts"
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: storage
  restartPolicy: Never

